# Changes here will be overwritten by Copier
_commit: 5.0.2
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: richard.cunningham@diamond.ac.uk
author_name: Richard Cunningham
description: A Neural Network to control the motion of the Deltabot stage.
distribution_name: deltabot-nn-controller
docker: false
docs_type: sphinx
git_platform: github.com
github_org: DiamondRC
package_name: deltabot_nn_controller
pypi: true
repo_name: deltabot-nn-controller
strict_typing: false
type_checker: pyright
